from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('loginUser', views.loginUser, name="loginUser"),
    path('logoutUser', views.logoutUser, name="logoutUser"),
    path('registerUser', views.registerUser, name="registerUser"),
    path('shop', views.shop, name="shop"),
    path('about', views.about, name="about"),
    path('singleNews/<int:newId>', views.singleNews, name="singleNews"),
    path('news', views.news, name="news"),
    path('contact', views.contact, name="contact"),
    path('cart', views.cart, name="cart"),
    path('buyNow/<uuid:product_id>/', views.buyNow, name ="buyNow"),
    path('checkout', views.checkout, name="checkout"),
    path('check', views.check, name="check"),
    path('forgotPassword',views.forgotPassword_input_email,name = "forgotPassword"),
    path('forgotPassword_2',views.forgotPassword_ResendOrDone,name="forgotPassword_2"),
    path('forgotPassword_3',views.forgotPassword_Reset,name="forgotPassword_3"),
    path('orderSuccess',views.orderSuccess,name="orderSuccess"),
    path('product/<uuid:productId>',views.productDetail,name="productDetail"),
    path('add_to_cart/<uuid:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('add_to_favourite/<uuid:product_id>/', views.add_to_favourite, name="add_to_favourite"),
    path('remove_from_cart/<uuid:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('search',views.search,name="search"),
    path('verify_otp',views.verify_otp,name = 'verify_otp'),
    path('checkout_buynow',views.checkout_buynow,name="checkout_buynow"),
    path('api/cart_count_api',views.cart_count,name="cart_count_api"),
    path('liked', views.liked, name="liked"),
    path('remove_from_liked/<uuid:liked_id>/', views.remove_from_liked, name="remove_from_liked"),
    path('voucher', views.voucher, name="voucher"),
    path('order', views.order, name="order"),
    path('profile', views.profile, name="profile"),
    path('remove_from_orderitem/<uuid:orderitem_id>/', views.remove_from_orderitem, name="remove_from_orderitem"),
]